package com.microdb.microdb.controller;

import java.util.Optional;

import javax.validation.Valid;

import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.NestedExceptionUtils;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.microdb.microdb.bean.Respuesta;
import com.microdb.microdb.bean.User;
import com.microdb.microdb.repository.UserRepository;

import io.swagger.v3.oas.annotations.parameters.RequestBody;


@Controller // This means that this class is a Controller
@RequestMapping(path = "/user") // This means URL's start with /demo (after Application path)
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    
    @PostMapping(path = "/add") // Map ONLY POST Requests
    @ExceptionHandler(DataIntegrityViolationException.class)
    public @ResponseBody Respuesta addNewUser(@RequestParam String name, @RequestParam String email, @RequestParam String documentNumber, @Valid @RequestParam(required = false) String cellPhoneNumber) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        n.setDocumentNumber(documentNumber);
        if(cellPhoneNumber != null && !cellPhoneNumber.isEmpty()){
            n.setCellPhoneNumber(cellPhoneNumber);
        }
        Respuesta respuesta = new Respuesta();
        try {
            userRepository.save(n);
            respuesta.setRespuesta("Usuario Guardado");
        } catch (DataIntegrityViolationException   e) {
            respuesta.setRespuesta("Usuario no fue guardado");
            respuesta.setError(NestedExceptionUtils.getMostSpecificCause(e).getMessage());
        }

        return respuesta;

    }

    @PostMapping(value = "/add2", consumes = "application/json", produces = "application/json")
    public @ResponseBody User addNewUser2(@RequestBody User user) {
        return userRepository.save(user);

    }

    @GetMapping(value = "/find", consumes = "application/json", produces = "application/json")
    public @ResponseBody Optional<User> getUser(@RequestBody User user) {
        return userRepository.findById(user.getId());

    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}